routes:
  - path: "/signup"
    method: "POST"
    request_filters:
      - remote_server: "http://10.106.248.129/auth/signup"
        request_format:
          Content-Type: "application/json"
        fields_to_send: ["username", "password", "email", "role"]
    handler_type: "signup"

  - path: "/signin"
    method: "POST"
    request_filters:
      - remote_server: "http://10.106.248.129/auth/login"
        request_format:
          Content-Type: "application/json"
        fields_to_send: ["username", "password"]
    handler_type: "login"
    
  - path: "/verify"
    method: "POST"
    handler_type: "verify"


jwt_config:
  secret_key: "12345667"
  required_fields:
    - "username"
