routes:
  - path: "/api/signup"
    method: "POST"
    request_filters:
      - remote_server: "http://a.a.a.a:80/validate"
        request_format:
          Content-Type: "application/json"
          X-Custom-Header: "value"
        fields_to_send: ["username", "password"]