# docker/Dockerfile.OpenAuth
FROM golang:1.23 AS builder

WORKDIR /app
COPY . .
RUN make build-server

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/build/OpenAuth .
EXPOSE 8080
ENTRYPOINT ["/app/OpenAuth"]