routes:
  - path: "/api/resource"
    method: "POST"
    request_filters:
      - remote_server: "http://a.a.a.a:80/validate"
        request_format:
          Content-Type: "application/json"
          X-Custom-Header: "value"
        fields_to_send: ["username", "password"]
    condition_filter:
      conditions:
        - field: "header"
          operator: "equals"
          value: "X-Auth-Token"
        - field: "query"
          operator: "contains"
          value: "version"
    proxy:
      target: "http://backend-service"
      timeout: 30