# oauth-sa.yaml
# OpenAuth 서버는 oauth-admin ServiceAccount로 실행되어 TokenReview API를 호출
# oauthctl은 oauth-configurator ServiceAccount로 실행되어 OpenAuth 서버에 인증
# OpenAuth 서버는 oauth-configurator ServiceAccount의 토큰만 허용

---
# OpenAuth 서버용 ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth-admin
  namespace: kube-system
---
# oauthctl용 ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth-configurator
  namespace: default
---
# TokenReview API 접근을 위한 ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: token-reviewer
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
---
# OpenAuth 서버에 TokenReview 권한 부여
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oauth-admin-token-reviewer
subjects:
  - kind: ServiceAccount
    name: oauth-admin
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: token-reviewer
  apiGroup: rbac.authorization.k8s.io