# oauth-sa.yaml
# OpenAuth 서버는 oauth-admin ServiceAccount로 실행되어 TokenReview API를 호출
# oauthctl은 oauth-configurator ServiceAccount로 실행되어 OpenAuth 서버에 인증
# OpenAuth 서버는 oauth-configurator ServiceAccount의 토큰만 허용

---
# OpenAuth 서버용 ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth-admin
---
# oauthctl용 ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth-configurator
---
# oauth-configurator Token Secret
apiVersion: v1
kind: Secret
metadata:
  name: oauth-configurator-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: oauth-configurator
type: kubernetes.io/service-account-token
---
# TokenReview API 접근을 위한 ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: token-reviewer
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
---
# 토큰 읽기 권한 제공
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-oauth-configurator-token
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["oauth-configurator-token"]
    verbs: ["get"]
---
# OpenAuth 서버에 TokenReview 권한 부여
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oauth-admin-token-reviewer
subjects:
  - kind: ServiceAccount
    name: oauth-admin
    namespace: default
roleRef:
  kind: ClusterRole
  name: token-reviewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-oauth-configurator-token-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: oauth-admin
    namespace: default
roleRef:
  kind: Role
  name: read-oauth-configurator-token
  apiGroup: rbac.authorization.k8s.io