---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openauth
  template:
    metadata:
      labels:
        app: openauth
    spec:
      serviceAccountName: oauth-admin
      containers:
        - name: openauth
          image: hochacha/openauth:1218_21
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"